# Generated by Django 4.2.23 on 2025-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='quantity',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
