# Generated by Django 4.2.23 on 2025-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_quantity_post_weight_post_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Раздел', max_length=100, unique=True),
        ),
    ]
